### ISSUE TITLE
Zig 0.14-dev error: no field named 'Struct' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'

### ISSUE THREAD

**Issue by FObersteiner** [n0s4/flags#10]
Hi there, I tried to build a project that uses `flags` with the latest master branch of Zig, and it throws this error at me. I guess this problem is due to a change in Zig std, so not actually an issue of `flags` but for `flags`... Maybe you already encoutered it, and found a solution? Or maybe I'm doing something wrong here? Didn't find a mention of this issue on ziggit.dev either...

This is also reproducible for `flags` examples; full error output:
```text
>>> zig version && zig build run-example
0.14.0-dev.1421+f87dd43c1
run-example
└─ run example
   └─ zig build-exe example Debug native 1 errors
src/meta.zig:35:30: error: no field named 'Struct' in enum '@typeInfo(builtin.Type).@"union".tag_type.?'
    if (@typeInfo(Flags) != .Struct) {
                            ~^~~~~~
/home/floo/Software/Zig/zig-linux-x86_64-0.14.0-dev/lib/std/builtin.zig:257:18: note: enum declared here
pub const Type = union(enum) {
                 ^~~~~
src/core.zig:67:27: note: called from here
    const info = meta.info(Flags);
                 ~~~~~~~~~^~~~~~~
referenced by:
    parseWithTrailingHandler__anon_3173: src/parser.zig:178:22
    parse__anon_2068: src/parser.zig:39:36
    6 reference(s) hidden; use '-freference-trace=8' to see all references
```

**Comment by joegm** [comment]
Yeah, apparently the `std.builtin.Type` variants were all changed to snake case. I've pushed a commit that fixes them. Here's the latest commit url you can use in your build.zig.zon:
https://github.com/n0s4/flags/archive/45b5e26a507cda792d92d0bf215af4a167142f68.tar.gz

**Comment by FObersteiner** [comment]
Thanks a lot! I took a look at the std source but didn't notice the case change 🤯
