### ISSUE TITLE
Feature request: show default values in help text

### ISSUE THREAD

**Issue by jeffective** [n0s4/flags#11]
Thanks for making this awesome library!!

Would it be possible to show the default values in the help menu?

For example:

```zig
// CLI options
const Flags = struct {
    // Optional description of the program.
    pub const description =
        \\The GatorCAT CLI.
    ;
    // sub commands
    command: union(enum) {
        // scan bus
        scan: struct {
            ifname: []const u8,
            recv_timeout_us: u32 = 10000,
            eeprom_timeout_us: u32 = 10000,
            pub const descriptions = .{
                .ifname = "Network interface to use for the bus scan.",
                .recv_timeout_us = "Frame receive timeout in microseconds.",
                .eeprom_timeout_us = "SII EEPROM timeout in microseconds.",
            };
        },
    },
};
```

Produces:
```
gatorcat scan -h
Usage: gatorcat scan --ifname <ifname> [--recv-timeout-us <recv-timeout-us>]
                     [--eeprom-timeout-us <eeprom-timeout-us>] [-h | --help]

Options:

  --ifname            Network interface to use for the bus scan.
  --recv-timeout-us   Frame receive timeout in microseconds.
  --eeprom-timeout-us SII EEPROM timeout in microseconds.
  -h, --help          Show this help and exit
```

The help text could perhaps say that `<eeprom-timeout-us> defaults to 10000` somewhere.

**Comment by jeffective** [comment]
If you like this idea and have a way you think it should look exactly, I could make an attempt at a PR.

**Comment by joegm** [comment]
I'm not sure whether this is worth implementing as we'd also have to deal with the case where the user does not want it for certain fields, and some users may wish to communicate the default value in a different way than some auto-generated '`(default=10000)`' tagged on.

The user can put this information in the `descriptions` entry for the field, so they can decide exactly how it is displayed and whether it is displayed at all very easily.
