### ISSUE TITLE
Support `[:0] const u8` arguments

### ISSUE THREAD

**Issue by jeffective** [n0s4/flags#14]
Use case: parse a string from command line arguments and directly pass it to a c-API that expects a null terminated string.

The current support for `[] const u8` requires an allocation or bounded array etc if it needs to be transformed to a null terminated string.

I`m not super sure but I think at least Linux and Windows provide null terminated strings already, so this could be done without allocation for both the null terminated and non-null terminated cases.

**Comment by joegm** [comment]
Good idea. Just pushed this to main (https://github.com/n0s4/flags/commit/119c1956099e987b5dea2792faa2c27e9b72dc61)
