### ISSUE TITLE
Debug print

### ISSUE THREAD

**Issue by FObersteiner** [n0s4/flags#4]
this line
https://github.com/n0s4/flags/blob/a540f9658d83526e58bf99dbd53a975855ef4d90/src/core.zig#L183
prints to the console whenever a debug mode build is compiled that uses `flags`. I guess this is a residue from debugging `flags` itself?

p.s. I really like the new version 0.6.0 :)

**Comment by joegm** [comment]
Woops.

p.s. thank you :)

**Comment by joegm** [comment]
Fixed on main.
