### ISSUE TITLE
Can switches be numbers?

### ISSUE THREAD

**Issue by FObersteiner** [n0s4/flags#5]
at the moment, switches must be characters:
https://github.com/n0s4/flags/blob/a540f9658d83526e58bf99dbd53a975855ef4d90/src/validate.zig#L44
is there a specific reason for this? For example, I [wanted to use](https://github.com/FObersteiner/ntp-client/blob/bf0d65c741fa925c1229319c95590409226b63cb/src/cmd.zig#L38) `-4` to specify "IPv4" (as opposed to IPv6).

**Comment by joegm** [comment]
Yeah this could be allowed.

**Comment by joegm** [comment]
Implemented on main: https://github.com/n0s4/flags/commit/e8e6a53f128633a53ac6937d9fdde65a96ea55fe.
You can update your dependency to point to this commit hash.

**Comment by FObersteiner** [comment]
> Implemented on main: [e8e6a53](https://github.com/n0s4/flags/commit/e8e6a53f128633a53ac6937d9fdde65a96ea55fe). You can update your dependency to point to this commit hash.

nice, thanks a lot!

**Comment by FObersteiner** [comment]
@n0s4 I think in v0.7.0 (v0.8.0?), the requirement for switches to be letters was re-introduced. Was that intentional?

**Comment by joegm** [comment]
No, my mistake. I just fixed this in the latest commit: https://github.com/n0s4/flags/commit/4f9d3dfd2de979dc199ab362d9f498cf7e4e7d9f

**Comment by FObersteiner** [comment]
> No, my mistake. I just fixed this in the latest commit: [4f9d3df](https://github.com/n0s4/flags/commit/4f9d3dfd2de979dc199ab362d9f498cf7e4e7d9f)

cool! I'll make sure to check sooner next time, after your next release :)
