### ISSUE TITLE
Improved auto-generated help text for positional arguments

### ISSUE THREAD

**Issue by GigaGrunch** [n0s4/flags#6]
With no help texts or descriptions defined, I get a wonderful error about missing positional arguments.
```
➜  trecker ./zig-out/bin/trecker.exe start
error: missing required argument: <PROJECT_ID>.
```
I don't get the same information in the auto-generated help text though. I'm expecting the positional arguments to be listed in there, but they are not mentioned at all.
```
➜  trecker ./zig-out/bin/trecker.exe start -h
Usage: command start [options]

Options:
  -h, --help Show this help and exit
```

**Comment by joegm** [comment]
Yes. I'm working on an update now that will include this.

**Comment by joegm** [comment]
https://github.com/n0s4/flags/releases/tag/v0.7.0
